// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qypxekyjsdzbobmirznk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF5cHhla3lqc2R6Ym9ibWlyem5rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MjI2MzMsImV4cCI6MjA3MzI5ODYzM30.tRoAZvFJp8W5r5vy5AwXlggEkljPpvt0_-T4i6OmnZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});